### ISSUE TITLE
[Bug] Solaire-mode changes background on the right of company drop-downs too

### ISSUE THREAD

**Issue by ianyepan** [hlissner/emacs-solaire-mode#37] opened 2020-08-18 03:17 UTC
As titled, `solaire-mode` is changing the background color on the right of company drop downs too. See the screenshot for details:

![image](https://user-images.githubusercontent.com/36686900/90466341-20a60b80-e144-11ea-88da-371ae7aebb7f.png)

![image](https://user-images.githubusercontent.com/36686900/90466364-3287ae80-e144-11ea-9235-58994dd7579b.png)

**Comment by hlissner** [comment] 2020-08-18 04:29
I cannot reproduce this in vanilla Emacs 26.3 or 27.1, on `doom-solarized-dark`, `doom-one` or `doom-dracula`. Can you tell me more about your Emacs environment? And what theme you're using?

**Comment by ianyepan** [comment] 2020-08-18 04:42
I'm on Emacs 27.0.91 on Windows WSL (Ubuntu 18.04) running an X-server.

For the themes, I'm using doom-gruvbox and/or doom-solarized-dark. I suspect it's something wrong on my end, since no one else seems to have a similar issue.

**Comment by hlissner** [comment] 2020-08-18 04:52
It's just a hunch, but I suspect one of the `company-*` faces has an `:extend t` property on it, and it shouldn't. Likely `company-scrollbar-bg`. Try evaluating this, after your theme (and company) has loaded:

```elisp
(set-face-attribute 'company-scrollbar-bg nil :extend nil)
```

**Comment by ianyepan** [comment] 2020-08-18 04:58
Unfortunately, that doesn't seem to fix it. This only happens when solaire-mode is enabled, and I've made sure company-scrollbar-bg doesn't have the :extend property set to true.

**Comment by jessiehildebrandt** [comment] 2020-08-29 22:34
Running Emacs 26.3 through Crostini on ChromeOS, and just noticed the same issue:
![Screenshot 2020-08-29 at 6 28 23 PM](https://user-images.githubusercontent.com/40772633/91647203-fc8cd900-ea25-11ea-8582-3a6084e1526e.png)
I've double-checked all of my faces, and none have an unnecessary `extend: t` property. Will double-check my primary Linux machine that is running Emacs 27.1 when I get back to it, because I don't remember noticing the issue there.

**Comment by jessiehildebrandt** [comment] 2020-08-30 19:20
The issue is not present when running Emacs 27.1 on Fedora 32:
![Screenshot from 2020-08-30 15-16-16](https://user-images.githubusercontent.com/40772633/91667592-e2113900-ead3-11ea-8ba8-d3b339116888.png)

I'm using the exact same theme and config on both systems, so it could be an issue that's only present on some versions of Emacs before 27.1. I'll try compiling 27.1 on my Chromebook and see if that gets rid of the issue there.

@ianpan870102 would you able to test your setup on WSL with Emacs 27.1?

**Comment by ianyepan** [comment] 2020-08-31 03:10
> @ianpan870102 would you able to test your setup on WSL with Emacs 27.1?

I'll try to do that this week, currently I'm still running the beta version of Emacs 27 (27.0.91).

**Comment by hlissner** [comment] 2020-08-31 04:00
I suspect this is a regression that snuck into the pre-release version of Emacs (27.0.x) and was shortly fixed before the 27.1 release. I hope that's the case, because I don't think there is anything I can do to resolve this on the elisp side of things.

**Comment by ianyepan** [comment] 2020-08-31 05:39
Bad news... I just reinstalled my Emacs and upgraded it to 27.1.50 on Ubuntu 18.04. This issue persists when solaire-mode is turned on, but doesn't appear otherwise.

**Comment by jessiehildebrandt** [comment] 2020-08-31 21:44
The cause may be something related to some piece of state within the buffer or Emacs itself. I've just noticed that the issue has started occurring on the Fedora machine that was previously unaffected:
![Screenshot from 2020-08-31 17-15-57](https://user-images.githubusercontent.com/40772633/91769754-f45fa580-ebad-11ea-960d-1e4e76f4b13f.png)
This was while editing the same buffer that I took a screenshot of yesterday, in which the issue was _not_ occurring.

Unless there is a particular package to blame here, it may just be general Emacs quirkiness. Not sure what to make of this.

**Comment by hlissner** [comment] 2020-09-02 02:23
I can reproduce this now that I've updated company. It seems this was introduced in https://github.com/company-mode/company-mode/commit/e1d58370cf1f6b42b929376eab2193bfc0914381 (https://github.com/company-mode/company-mode/pull/996), which fontifies to EOL by hard-coding an anonymous face with `:extend t` into its overlays. Makes it pretty hard to fix. Not sure if it's really solaire-mode's responsibility _to_ fix it either. It applies to non-solaire-mode users as well, but their background color isn't changed so it's invisible to them.

**Comment by ianyepan** [comment] 2020-09-02 02:45
@hlissner Sweet, do you wish to open an issue over at company?

**Comment by hlissner** [comment] 2020-10-06 05:34
Sorry for the late follow up (I was on break). I've reported this upstream.

**Comment by ianyepan** [comment] 2020-10-06 05:36
Thank you @hlissner !

**Comment by hlissner** [comment] 2020-10-08 01:41
The PR was merged, so I will consider this resolved. Thanks for bringing it to my attention!

**Closed as completed by hlissner** 2020-10-08 01:41 UTC
Labels: bug
