### ISSUE TITLE
Solaire changes buffer-face-mode-face

### ISSUE THREAD

**Issue by trbjo** [hlissner/emacs-solaire-mode#8] opened 2018-04-24 09:31 UTC
I use two different fonts – one for org-mode and one for everything else. I believe the relevant part of my .emacs looks like this: 

>(set-face-attribute 'default nil :font "Fantasque Sans Mono-11")

> (add-hook 'org-mode-hook (lambda () (setq buffer-face-mode-face '(:family "Roboto")) (buffer-face-mode)))

Now, everytime I first open an org-mode file and then switch to e.g. a source code file, the source code file is now set with the Roboto font.

If I open the source code file first, however, the text is shown with Fantasque Sans Mono as it should.

I've tried playing around with the suggested lines to put in .emacs, and the culprit is this:

> (add-hook 'after-change-major-mode-hook #'turn-on-solaire-mode)

If I comment it out, the faces change just fine, but it renders solaire-mode unusable. 

I've tried using a different "definition" than buffer-face-mode-face, namely variable-pitch instead, and it's the same result. (I'm sorry if this sentence is non-sensical to you, my elisp is abysmally bad). 

What to do?

**Comment by hlissner** [comment] 2018-05-02 23:35
The problem is that `buffer-face-mode` and `solaire-mode` both try to remap the `default` face, and only one can succeed, without some face-remapping voodoo.

Give this a try:

```elisp
(add-hook 'org-mode-hook
  (lambda () (face-remap-add-relative 'solaire-default-face :family "Roboto")))
```

**Comment by trbjo** [comment] 2018-05-03 13:09
This is definitely better than before. Thank you!

The problem with the fonts is solved. The only thing solaire interferes with now is the background of the initial (scratch) buffer and the echo-area/minibuffer-prompt area below the modeline in the bottom of the frame. I've been unable to set it playing around with the different options you mention in the readme.

This is what I mean (I usually have no mode line in org-mode):
![udklip](https://user-images.githubusercontent.com/26080212/39579009-fe02ecc6-4ee5-11e8-87c3-5cc25a39bfcc.PNG)

Do you know if there is a way to change the color depending on whether the mode-line is shown/hidden?

**Comment by hlissner** [comment] 2018-05-03 15:36
The scratch buffer isn't considered a "real" buffer by solaire-mode, hence its background. i.e. "Real" buffers get highlighted. The default heuristic for what makes a buffer real is if `buffer-file-name` is non-nil (i.e. if it's a file-visiting buffer). 

You can change this by setting `solaire-mode-real-buffer-fn` to a function that returns `t` for the scratch buffer. Something like:

```elisp
(defun real-buffer-p (buffer)
  (or (solaire-mode--real-buffer-fn buffer)  ; is BUFFER a file visiting buffer?
      (string= (buffer-name buffer) "*scratch*")))
(setq solaire-mode-real-buffer-fn #'real-buffer-p)
```

There is no solution for the echo-area, however, because there's no way to give the whole minibuffer a (permanent) buffer-local background. This is a limitation of Emacs, unfortunately. The closest you'll get is `(add-hook 'minibuffer-setup-hook #'solaire-mode-in-minibuffer)`, which gives it a background _only while it's active_.

Alternatively, you could change `solaire-mode-real-buffer-fn` to return nil for org buffers (or buffers where `mode-line-format` is nil), then they'll share the same background as the echo-area.

**Comment by hlissner** [comment] 2018-06-15 17:45
I'll assume I've answered your question and can close this issue. Feel free to reopen this otherwise!

**Closed as completed by hlissner** 2018-06-15 17:45 UTC
Labels: question

**Comment by alphapapa** [comment] 2018-12-25 15:19
@hlissner Thank you for answering this question.  I've long done a similar thing, using this in my `org-mode-hook`:

```el
(buffer-face-set :family (face-attribute 'variable-pitch :family))
```
Then when I tried `solaire-mode`, I noticed that all of my source code buffers were using variable pitch, and I couldn't find any apparent reason, even when checking every face that was applied to some text.

Thankfully I found this issue.  So I replaced that code with:

```el
(face-remap-add-relative 'default :inherit 'variable-pitch)
```
And *after restarting Emacs*, it seems to have fixed the problem, and I still get variable pitch in Org buffers!

BTW, I don't understand exactly how `buffer-face-mode` and `face-remap` work and how they differ.  Could you explain it simply, if it's possible?  :)  If you can, I'll add it to https://github.com/alphapapa/emacs-package-dev-handbook for future reference.

**Comment by alphapapa** [comment] 2018-12-25 19:12
Apparently I spoke too soon, as after restarting Emacs again, the problem returns.  That is:

1.  I start Emacs with this code in my `org-mode-hook`:

```el
(face-remap-add-relative 'default :inherit 'variable-pitch)
```
2.  Load an Org file.  It's in variable pitch.
3.  Load an elisp file.  It's in monospace.
4.  Load solaire with this code:
```el
(use-package solaire-mode
  :hook
  ((change-major-mode after-revert ediff-prepare-buffer) . turn-on-solaire-mode)
  (minibuffer-setup . solaire-mode-in-minibuffer))
```
5.  Load another Org file.
6.  Load another elisp file.  It's in variable pitch!

Trying to follow @hlissner's example, I added this to my `org-mode-hook' before the code in step 1:
```el
(face-remap-add-relative 'solaire-default-face :family (face-attribute 'default :family))
```
But that didn't make any difference.

I guess either I'm doing something wrong, or solaire isn't compatible with any other code that does face remapping...?
